name: Sync with upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada hora (puedes ajustar esto)
  workflow_dispatch:      # Permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream and sync
        run: |
          git remote add upstream https://github.com/UFV-INGINF/BookHunt
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories || echo "No changes to merge"
          git push origin main
